version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: todoapi_postgres
    restart: always
    environment:
      POSTGRES_DB: todo_api
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1801
    volumes:
      - ./test/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
