### Create task
POST http://localhost:8080/v1/tasks
Content-Type: application/json
X-API-Key: super-secret-api-key

{
  "title": "Learn go faster 2"
}

> {%
    client.global.set("taskId", response.body.id);
%}

### Get ALL tasks
GET http://localhost:8080/v1/tasks
Content-Type: application/json

### Get task by Task ID
GET http://localhost:8080/v1/tasks/{{taskId}}
Content-Type: application/json


### Update task
PUT http://localhost:8080/v1/tasks/{{taskId}}
Content-Type: application/json
X-API-Key: super-secret-api-key

{
  "title": "Learn to Go updated",
  "completed": true
}
### Delete task
DELETE http://localhost:8080/v1/tasks/{{taskId}}
Content-Type: application/json
X-API-Key: super-secret-api-key



